
CREATE table IF NOT EXISTS projects (
id INTEGER IDENTITY PRIMARY KEY,
  domain varchar(64),
  sub_domain varchar(64),
  start_date Date,
  hours int
);

CREATE TABLE IF NOT EXISTS PRACTICE (
  ID INTEGER IDENTITY PRIMARY KEY,
  PROJECT_ID INTEGER,
  PRACTICE_DATE DATE,
  HOURS INTEGER,
  NOTE VARCHAR(255),
  FOREIGN KEY (PROJECT_ID) references PROJECTS(ID) ON DELETE CASCADE
);